TemplateDemo/Controllers/KPIController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TemplateDemo.Models;
using BAEClassLibrary;
using Newtonsoft.Json;
using System.Data.Entity.Validation;
using System.Data.Entity;

namespace TemplateDemo.Controllers
{
    public class KPIController : BAEController
    {
        BAETDDB db = new BAETDDB();
        // GET: KPI
        public ActionResult Index()
        {
             AnswerResult ar = (AnswerResult)TempData["AnswerResult"] ?? new AnswerResult(); TempData["AnswerResult"] = null;
            ViewBag.AnswerResult = JsonConvert.SerializeObject(ar);
            return View();
        }
        public ActionResult ReadKPIS([DataSourceRequest] DataSourceRequest request)
        {
            IList<KPIViewModel> list = db.KPIS.Select(s=> new KPIViewModel()
            {
                 KPIID =s.KPIID,
                 AppName =s.AppName,
                 KPIName =s.KPIName,
                 KPIDescription =s.KPIDescription,
                 Active =s.Active,
                 Url =s.Url
            }).ToList();
            return Json(list.ToDataSourceResult(request));
        }
        public ActionResult Detail(int? id)
        {
            AnswerResult ar = (AnswerResult)TempData["AnswerResult"] ?? new AnswerResult(); TempData["AnswerResult"] = null;
            KPIS eq = id != null && id != 0 ? db.KPIS.FirstOrDefault(a => a.KPIID == id) : new KPIS() { Active = true };
            ViewBag.Action = eq.KPIID != 0 ? "Edit" : "Create";
            ViewBag.AppName = db.Menu.Select(a=>a.AppName).Distinct().Select(c => new SelectListItem
            {
                Value = c.ToString(),
                Text =c.ToString()
            }).OrderBy(a => a.Text);
            ViewBag.AnswareResult = JsonConvert.SerializeObject(ar);
            return View(eq);
        }
        [HttpPost]
        public ActionResult Create(KPIS kpi)
        {
            AnswerResult ar = new AnswerResult();
            if (ModelState.IsValid)
            {
                try
                {
                    db.KPIS.Add(kpi);
                    db.SaveChanges();
                    ar.Type.Add(1);
                    ar.Messages.Add(Resources.AnswerResultSuccess);
                    ar.ID = kpi.KPIID;
                }
                catch (DbEntityValidationException E)
                {
                    ar.Type.Add(3);
                    ar.Messages.Add(Resources.AnswerResultError);
                    foreach (var eve in E.EntityValidationErrors)
                    {
                        foreach (var ve in eve.ValidationErrors)
                        {
                            ar.Type.Add(3);
                            ar.Messages.Add(ve.ErrorMessage.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                        }
                    }
                }
                catch (Exception E)
                {
                    ar.Type.Add(3);
                    ar.Messages.Add(Resources.AnswerResultError);
                    if (E.InnerException != null)
                    {
                        ar.Type.Add(3);
                        ar.Messages.Add(E.InnerException.InnerException.Message.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                    }
                    else
                    {
                        ar.Type.Add(3);
                        ar.Messages.Add(E.Message.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                    }

                }
            }
            return Json(ar);
        }
        [HttpPost]
        public ActionResult Edit(KPIS kpi)
        {
            AnswerResult ar = new AnswerResult();
            if (ModelState.IsValid)
            {
                try
                {
                    db.KPIS.Attach(kpi);
                    db.Entry(kpi).State = EntityState.Modified;
                    db.SaveChanges();
                    ar.Type.Add(1);
                    ar.ID = kpi.KPIID;
                    ar.Messages.Add(Resources.AnswerResultSuccess);
                }
                catch (DbEntityValidationException E)
                {
                    ar.Type.Add(3);
                    ar.Messages.Add(Resources.AnswerResultError);
                    foreach (var eve in E.EntityValidationErrors)
                    {
                        foreach (var ve in eve.ValidationErrors)
                        {
                            ar.Type.Add(3);
                            ar.Messages.Add(ve.ErrorMessage.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                        }
                    }
                }
                catch (Exception E)
                {
                    ar.Type.Add(3);
                    ar.Messages.Add(Resources.AnswerResultError);
                    if (E.InnerException != null)
                    {
                        ar.Type.Add(3);
                        ar.Messages.Add(E.InnerException.InnerException.Message.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                    }
                    else
                    {
                        ar.Type.Add(3);
                        ar.Messages.Add(E.Message.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                    }

                }
            }

            return Json(ar);
        }
        public ActionResult ShowDeleteConfirmation(int id)
        {
            KPIS eq = db.KPIS.FirstOrDefault(a => a.KPIID == id);
            //verificamos que no tenga dependencias 
            ViewBag.EntryFound = false;
            if (eq.DashboardUser.Count > 0)
            {
                ViewBag.EntryFound = true;
            }
            return PartialView(eq);
        }
        [HttpPost]
        public ActionResult Delete(KPIS kpi)
        {
            AnswerResult ar = new AnswerResult();
            try
            {
                KPIS k = db.KPIS.FirstOrDefault(a => a.KPIID == kpi.KPIID);
                db.KPIS.Attach(k);
                db.KPIS.Remove(k);
                db.SaveChanges();
                ar.Type.Add(1);
                ar.Messages.Add(Resources.AnswerResultSuccess);
            }
            catch (DbEntityValidationException E)
            {
                ar.Type.Add(3);
                ar.Messages.Add(Resources.AnswerResultError);
                foreach (var eve in E.EntityValidationErrors)
                {
                    foreach (var ve in eve.ValidationErrors)
                    {
                        ar.Type.Add(3);
                        ar.Messages.Add(ve.ErrorMessage.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                    }
                }
            }
            catch (Exception E)
            {
                ar.Type.Add(3);
                ar.Messages.Add(Resources.AnswerResultError);
                if (E.InnerException != null)
                {
                    ar.Type.Add(3);
                    ar.Messages.Add(E.InnerException.InnerException.Message.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                }
                else
                {
                    ar.Type.Add(3);
                    ar.Messages.Add(E.Message.Replace("'", "").Replace("\"", "").Replace("\r\n", "  "));
                }

            }
            return Json(ar);
        }
        public ActionResult MyDashboard()
        {
            AnswerResult ar = new AnswerResult();
            ViewBag.AnswareResult = JsonConvert.SerializeObject(ar);
            return View(db.DashboardUser.Where(a => a.EmployeeID == UserContext.current.EmployeeID).ToList());
        }
        [HttpPost]
        public ActionResult MyDashboardResize(List<predashboard> listDash)
        {
            AnswerResult ar = new AnswerResult();
            ar.Messages.Add(Resources.AnswerResultSuccess);
            ar.Type.Add(1);
            foreach (var item in listDash)
            {
                DashboardUser dh = db.DashboardUser.FirstOrDefault(a => a.DashboardID == item.DashboardID);
                if (dh != null)
                {
                    try
                    {
                        dh.datax = item.x;
                        dh.datay = item.y;
                        dh.datah = item.h;
                        dh.dataw = item.w;
                        db.Entry(dh).State = EntityState.Modified;
                        db.SaveChanges();

                    }
                    catch (Exception ex)
                    {
                        ar.Messages.Clear();
                        ar.Type.Clear();
                        ar.Messages.Add(Resources.AnswerResultError);
                        ar.Type.Add(3);
                        ar.Messages.Add(ex.ToString());
                        ar.Type.Add(3);
                    }
                }

            }

            return Json(ar);
        }
        [HttpPost]
        public ActionResult MyDashboardDelete(int DashboardID)
        {
            AnswerResult ar = new AnswerResult();
            try
            {
                DashboardUser dh = db.DashboardUser.FirstOrDefault(a => a.DashboardID == DashboardID);
                if (dh != null)
                {

                    db.DashboardUser.Attach(dh);
                    db.DashboardUser.Remove(dh);
                    db.SaveChanges();
                    ar.Messages.Add(Resources.AnswerResultSuccess);
                    ar.Type.Add(1);
                }
            }
            catch (Exception ex)
            {
                ar.Messages.Add(Resources.AnswerResultError);
                ar.Type.Add(3);
                ar.Messages.Add(ex.ToString());
                ar.Type.Add(3);
            }

            return Json(ar);
        }
        public ActionResult AddKPI(int kpiid)
        {

TemplateDemo/Views/NotificationManager/Index.cshtml
<div class="row">
    <div class="col-lg-12">
        <div class="kt-portlet kt-portlet--tabs kt-portlet--last kt-portlet--responsive-mobile" id="kt_page_portlet">
            <div class="kt-portlet__head ">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">@BAEClassLibrary.Resources.Notifications <small>@BAEClassLibrary.Resources.Administrator @BAEClassLibrary.Resources.Of @BAEClassLibrary.Resources.Notifications</small></h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <ul class="nav nav-tabs nav-tabs-line nav-tabs-line-right" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#ListTab" role="tab">
                                <i class="fa fa-list"></i>
                                @BAEClassLibrary.Resources.List
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#DetailTab" role="tab">
                                <i class="fa fa-file"></i>
                                @BAEClassLibrary.Resources.Detail
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="tab-content">
                    <div class="tab-pane active" id="ListTab">
                        @(Html.Kendo().Grid<TemplateDemo.Models.NotificationList>()
                                           .Name("grid")
                                       .ToolBar(tools =>
                                       {
                                       tools.Template(@<text>
                                                    <a class="k-button k-button-icontext k-grid-excel" href="#"><span class="k-icon k-i-excel"></span>@BAEClassLibrary.Resources.Export @BAEClassLibrary.Resources.To Excel</a>
                                                    <button class="k-button k-button-icontext" type="button" onclick="GetTabDetail(0)"><span class="k-icon k-i-add"></span>@BAEClassLibrary.Resources.New </button>

                                    </text>
);
                                       })
.ColumnMenu()
.Scrollable()
.AutoBind(true)
.DataSource(data => data
.Ajax()
.PageSize(50)
.Model(model =>
{
    model.Id(a => a.NotificationListID);
    model.Field(a => a.Apps.AppName).Editable(false);
    model.Field(a => a.Subject).Editable(false);
    model.Field(a => a.Message).Editable(false);
    model.Field(a => a.Active).Editable(false);
    model.Field(a => a.NotificationType).Editable(false);
    model.Field(a => a.AlertType).Editable(false);
    model.Field(a => a.Icon).Editable(false);
    model.Field(a => a.Link).Editable(false);
})

.Read(read => read.Action("ReadNotificationList", "NotificationManager",new { AppID = Model.AppID }))
.Events(a => a.Error("ShowError"))
)
.Columns(col =>
{
    col.Bound(bo => bo.NotificationListID).Hidden();
    col.Bound(bo => bo.Apps.AppName).Title(BAEClassLibrary.Resources.AppName);
    col.Bound(bo => bo.Subject).Title(BAEClassLibrary.Resources.Title);
    col.Bound(bo => bo.Message).Title(BAEClassLibrary.Resources.Message);
    col.Bound(bo => bo.Active).ClientTemplate(
                                                      "# if (Active == 0) { #" +
                                                      "<span class='kt-badge kt-badge--danger kt-badge--inline kt-badge--pill kt-badge--md '><i class='fa fa-times'></i>&nbsp;No</span>" +
                                                      "" +
                                                      "# } else  { #" +
                                                      "<span class='kt-badge kt-badge--success kt-badge--inline kt-badge--pill kt-badge--md '><i class='fa fa-check'></i>&nbsp;" + BAEClassLibrary.Resources.Yes + "</span>" +
                                                      "# } #"
                                                      ).Title(BAEClassLibrary.Resources.Active);
    col.Bound(bo => bo.NotificationType).ClientTemplate(
                                                      "# if (NotificationType == 1) { #" +
                                                      BAEClassLibrary.Resources.Notification +
                                                      "# } else if (NotificationType == 2) { #" +
                                                        BAEClassLibrary.Resources.Event +
                                                      "# } else { #" +
                                                       BAEClassLibrary.Resources.Log +
                                                      "# } #"
                                                      ).Title(BAEClassLibrary.Resources.NotificationType);
    col.Bound(bo => bo.AlertType).ClientTemplate(
                                                      "# if (AlertType == 1) { #" +
                                                       "<span class='kt-badge kt-badge--success kt-badge--inline kt-badge--pill kt-badge--md '><i class='fa fa-times'></i>&nbsp;"+BAEClassLibrary.Resources.Success +"</span>"+
                                                      "# } else if (AlertType == 2) { #" +
                                                      "<span class='kt-badge kt-badge--warning kt-badge--inline kt-badge--pill kt-badge--md '><i class='fa fa-times'></i>&nbsp;"+BAEClassLibrary.Resources.Warning +"</span>"+
                                                         "# } else if (AlertType == 3) { #" +
                                                       "<span class='kt-badge kt-badge--danger kt-badge--inline kt-badge--pill kt-badge--md '><i class='fa fa-times'></i>&nbsp;"+BAEClassLibrary.Resources.Danger +"</span>"+
                                                         "# } else if (AlertType == 4) { #" +
                                                        "<span class='kt-badge kt-badge--info kt-badge--inline kt-badge--pill kt-badge--md '><i class='fa fa-times'></i>&nbsp;"+BAEClassLibrary.Resources.Informative +"</span>"+
                                                      "# } else { #" +
                                                        "<span class='kt-badge kt-badge--brand kt-badge--inline kt-badge--pill kt-badge--md '><i class='fa fa-times'></i>&nbsp;"+BAEClassLibrary.Resources.Brand +"</span>"+
                                                      "# } #"
                                                      ).Title(BAEClassLibrary.Resources.AlertType);
    col.Bound(bo => bo.Icon).Title(BAEClassLibrary.Resources.Icon);
    col.Bound(bo => bo.Link);
    col.Command(command =>
    {
        //command.Custom(BAEClassLibrary.Resources.Detail + "PopUP").Click("ShowWindowEdit");
        command.Custom("Detail").Click("GetTabDetail").Template("<a role=\"button\" class=\"btn btn-info btn-sm btn-icon k-grid-Detail\"> <i class=\"fa fa-eye\"></i></a>");
    }).Width(170).Title(@BAEClassLibrary.Resources.Options);
})
.Pageable(pageable => pageable
.PageSizes(true)
.Refresh(true)
.ButtonCount(5)
)
.Pdf(pdf => pdf.Title("Export" + DateTime.Now.Date + ".pdf"))
.Excel(xl =>
{
    xl.FileName("Export" + DateTime.Now.Date + ".xlsx");
    xl.AllPages(true);
})
.Filterable(filter => filter.Mode(GridFilterMode.Row))
.Resizable(resize => resize.Columns(true))
.HtmlAttributes(new { style = "height: 670px;" })
                        )
                    </div>
                    <div class="tab-pane" id="DetailTab">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    //Inicio de Documento
    $(function () {
        //Verificamos si existe notificacion para mostrar
        GetAnswerNShowIT(JSON.parse('@Html.Raw(ViewBag.AnswerResult)'));
        //Buscamos un detalle sin ID para traernos el HTML por si cambia de tab sin elegir elemento, que no aparezca en blanco el contenedor del tab
        GetPartialView("@(Url.Action("Detail" , "NotificationManager"))", 'DetailTab');

    });
    //Nos traemos la vista parcial con el objeto dentro
    function GetTabDetail(id) {
       ShowTabDetail(id,"@(Url.Action(""))",'NotificationListID')
    }
    function GetCurrentAppID() {
        return {
            AppID: @Model.AppID
        };
    }
</script>

TemplateDemo/Views/NotificationManager/ShowDeleteConfirmation.cshtml
@model TemplateDemo.Models.NotificationList

@if (ViewBag.EntryFound)
{
    <p>@BAEClassLibrary.Resources.EntryFound</p>
}
else
{
    <div class="form-group row">
        <div class="col-sm-6">
            @Html.Label("ID Notification")
            @(Html.Kendo().TextBox().HtmlAttributes(new { @class = "form-control", disabled = "true" }).Value(Model.NotificationListID.ToString()).Name("DisplayKPIID"))
        </div>
        <div class="col-sm-6">
            @Html.Label(BAEClassLibrary.Resources.Active)
            @(Html.Kendo().TextBox().Name("Activo").Value(Model.Active ? BAEClassLibrary.Resources.Yes : "No").HtmlAttributes(new { @class = "form-control", disabled = "true" }))
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-6">
            @Html.Label(BAEClassLibrary.Resources.Title)
            @(Html.Kendo().TextBoxFor(a => a.Subject).HtmlAttributes(new { @class = "form-control", disabled = "true" }))
        </div>
        <div class="col-sm-6">
            @Html.Label(BAEClassLibrary.Resources.Message)
            @(Html.Kendo().TextBoxFor(a => a.Message).HtmlAttributes(new { @class = "form-control", disabled = "true" }))
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-6">
            @Html.Label(BAEClassLibrary.Resources.NotificationType)
            @(Html.Kendo().TextBox().Name("NotificationType").HtmlAttributes(new { @class = "form-control", disabled = "true", value = ViewBag.NotificationType }))
        </div>
        <div class="col-sm-6">
            @Html.Label(BAEClassLibrary.Resources.AlertType)
            @(Html.Kendo().TextBox().Name("AlertType").HtmlAttributes(new { @class = "form-control", disabled = "true", value = ViewBag.AlertType }))

        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-6">
            @Html.Label(BAEClassLibrary.Resources.Icon)
            @(Html.Kendo().TextBoxFor(a => a.Icon).HtmlAttributes(new { @class = "form-control", disabled = "true" }))
        </div>
        <div class="col-sm-6">
            @Html.Label("Link")
            @(Html.Kendo().TextBoxFor(a => a.Link).HtmlAttributes(new { @class = "form-control", disabled = "true" }))
        </div>
    </div>
}
<div class="form-group">
    @using (Html.BeginForm("Delete", "NotificationManager", FormMethod.Post, new { id = "NotificationListFormDelete" }))
    {
        @(Html.Kendo().TextBoxFor(a => a.NotificationListID).HtmlAttributes(new { @class = "form-control", type = "hidden" }))
        <div class=" pull-right">
            <button type="submit" class="btn btn-brand" disabled="@ViewBag.EntryFound" id="BtnSubmit">@BAEClassLibrary.Resources.Accept</button>
            <button type="button" class="btn btn-secondary" onclick="CloseWindow('deleteWindow')">@BAEClassLibrary.Resources.Cancel</button>
        </div>
    }
</div>

<script>
    $(function () {
        //centramos
        $("#deleteWindow").data("kendoWindow").center();

    });
     $("#NotificationListFormDelete").submit(function (e) {
        e.preventDefault();
        var formData = new FormData(this);
        $.ajax({
            url: this.action,
            type: this.method,
            data: new FormData(this),
            contentType: false,
            processData: false,
            success: function (obj) {
                GetAnswerNShowIT(obj);
                if (obj.Type[0] == 1) {
                    CloseWindow('deleteWindow');
                    GetPartialView("@(Url.Action("Detail" , "KPI"))", 'DetailTab');
                     $("#grid").data("kendoGrid").dataSource.read();
                }
            },
            error: function (requestObject, error, errorThrown) {
                $("#deleteWindow").data("kendoWindow").close();
                CreateAnswerNShowIt('@BAEClassLibrary.Resources.AnswerResultError' + JSON.stringify(requestObject), 3);
            }
        });
     });

</script>